In [4]:
def add_bias(X):
    return np.insert(X, 0, 1, axis=1)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))
def softmax(li):
    exp_of_li = np.exp(li)
    sum_of_exp_of_li = np.sum(exp_of_li, axis=1).reshape(-1, 1)
    return exp_of_li / sum_of_exp_of_li

def forward_pass(X, p1_weights, p2_weights):
    """
    X: girdi katmanı (Öznitelikler matrisi)
    p1_weights : 1.perceptronun ağırlık matrisi
    p2_weights : 2.perceptronun ağırlık matrisi
    """
    hidden_layer = sigmoid(np.matmul(add_bias(X), p1_weights))
    output_layer = softmax(np.matmul(add_bias(hidden_layer), p2_weights))
    return output_layer




In [5]:
hidden_layer = sigmoid(np.matmul(X, weights_1))
output_layer = softmax(np.matmul(hidden_layer, weights_2)) # 60000, 10

NameError: name 'X' is not defined

$softmax(l_i)=\frac{\exp{l_i}}{\sum\exp{l_i}} $

In [6]:
def softmax(li):
    exp_of_li = np.exp(li)
    sum_of_exp_of_li = np.sum(exp_of_li, axis=1).reshape(-1, 1)
    return exp_of_li / sum_of_exp_of_li

In [7]:
import numpy as np 

ex_data = np.array([[0.2, 0.4, 0.6], [0.1, 0.3, 0.5]])

ex_data, ex_data.shape

(array([[0.2, 0.4, 0.6],
        [0.1, 0.3, 0.5]]),
 (2, 3))

In [8]:
exp_data = np.exp(ex_data)
exp_data

array([[1.22140276, 1.4918247 , 1.8221188 ],
       [1.10517092, 1.34985881, 1.64872127]])

In [9]:
a = np.sum(exp_data, axis=1)
a.shape

b = a.reshape(-1, 1)

b, b.shape

(array([[4.53534626],
        [4.103751  ]]),
 (2, 1))

In [10]:
exp_data / np.sum(exp_data, axis=1).reshape(-1,1)

array([[0.2693075 , 0.32893292, 0.40175958],
       [0.2693075 , 0.32893292, 0.40175958]])

In [11]:
softmax(np.array([[1, 22]]))

array([[7.58256042e-10, 9.99999999e-01]])

In [12]:
softmax(np.array([[1, 1000]]))

<ipython-input-6-7e4df9a4c090>:2: RuntimeWarning: overflow encountered in exp
  exp_of_li = np.exp(li)
<ipython-input-6-7e4df9a4c090>:4: RuntimeWarning: invalid value encountered in true_divide
  return exp_of_li / sum_of_exp_of_li


array([[ 0., nan]])

In [13]:
# log softmax

# https://nolanbconaway.github.io/blog/2017/softmax-numpy

In [14]:
def classify_or_prediction(X, w1, w2):
        return np.argmax(forward_pass(X, w1, w2), axis=1).reshape(-1,1)

\begin{equation}
J(\theta) = CE({\boldsymbol y},\hat{\boldsymbol y}) = - \frac{1}{m}\sum^{\textrm{m}}_{i=1} y_{i}\log({\hat{y}}_{i})
\end{equation}

# Cross Entropy Loss

https://machinelearningmastery.com/cross-entropy-for-machine-learning/

In [15]:
def ce_loss(Y, Y_prediction):
    return -np.sum(Y * np.log(Y_prediction))/ Y.shape[0]